### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by peaceng** [povilasb/face-recognition#5]
excuse me sir, 
im student of computer engineering, i got a work to make realtime face recogniton and tracking with python, but im new on python.
greatfully i find this repository, so i try to understand the algorithm and try this code at my windows 7 cmd, 
but there is some problem when i do training and enter my name, the code do nothing after that and stop immediatly.

please help this boy to find out whats wrong, 
sorry if dont speak english well. :(

**Comment by povilasb** [comment]
Hi, no worries :)
I haven't really tested the code on Windows as I mostly develop for Linux platform, but sure I can help you with that ;)
Although, I really don't wanna spend too much time on this repo since the algorithm (https://en.wikipedia.org/wiki/Eigenface) used here doesn't work well in real life. This repo basically is just a demo. But I definitely wouldn't use this code for smth practical. See: https://github.com/povilasb/face-recognition/issues/1

Could you initially post some errors you're getting on windows so that we had some starting point?
In the mean time, I'll try to test that myself.

**Comment by peaceng** [comment]
thanks for reply sir, sorry to bother you :)

in #1 case, the unknown person detected as trained person. im still studying that issue

when i tried it myself i got this o my cmd.
`C:\Users\admin>python "D:\facerecvid\face-recognition-master\facerecognition\mai
n.py" train
Enter your name: aceng

C:\Users\admin>`

my webcame didnt show up
![my result](https://user-images.githubusercontent.com/33070799/36411227-23b1f6b0-1647-11e8-82c1-4ead9d070f57.png)

i think something wrong with my webcam, but i'm not sure about that.
i try to open my webcam with simple opencv code like 
"cap=cv2.VideoCapture() 
cv2.imshow('frame',gray)"
 and it show camera frame.

**Comment by peaceng** [comment]
sir. thank you for your reply, sorry if i bother you 
i think my problem solved,
i think the problem goes to my camera. i do some setting for my camera, and it works,

**Comment by povilasb** [comment]
great! :)
